import React from 'react';
import { Link } from 'react-router-dom';
import { Wand2, ArrowLeft } from 'lucide-react';

function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-[#1a0033] via-[#2d0059] to-[#1a0033]">
      <nav className="container mx-auto px-6 py-4">
        <div className="flex items-center justify-between">
          <Link to="/" className="flex items-center space-x-2">
            <Wand2 className="h-8 w-8 text-violet-400" />
            <span className="text-2xl font-bold text-white">PicGenV</span>
          </Link>
        </div>
      </nav>

      <div className="container mx-auto px-6 py-12">
        <Link to="/" className="inline-flex items-center text-violet-400 hover:text-white mb-8 transition">
          <ArrowLeft className="h-5 w-5 mr-2" />
          Back to Home
        </Link>

        <div className="bg-violet-900/30 p-8 md:p-12 rounded-2xl backdrop-blur-sm border border-violet-800/50">
          <h1 className="text-4xl font-bold text-white mb-8">Privacy Policy</h1>
          <p className="text-violet-300 mb-6">Last Updated: Sunday, 1 September 2024</p>

          <div className="space-y-8 text-violet-200">
            <section>
              <h2 className="text-2xl font-bold text-white mb-4">1. Introduction</h2>
              <p>Welcome to PicGenV! This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our Discord bot ("Bot"). By using PicGenV, you agree to the terms outlined in this policy.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white mb-4">2. Information We Collect</h2>
              <h3 className="text-xl font-semibold text-white mb-2">2.1 User Data</h3>
              <p>We collect the following types of information when you interact with PicGenV:</p>
              <p className="mt-2">Messages and Commands: We may temporarily store the content of commands and prompts you send to the bot for processing and generating images. This data is not stored permanently.</p>
              
              <h3 className="text-xl font-semibold text-white mt-4 mb-2">2.2 Generated Content</h3>
              <p>The images generated by PicGenV based on your prompts may be stored temporarily for delivery. However, we do not retain these images after they have been sent to you unless explicitly stated for specific features.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white mb-4">3. How We Use Your Information</h2>
              <p>We use the collected information for the following purposes:</p>
              <ul className="list-disc list-inside mt-2 space-y-2">
                <li>Provide Services: To process your prompts and generate images as requested.</li>
                <li>Improve Functionality: To enhance the bot's features, performance, and user experience.</li>
                <li>Statistics: To analyze bot usage, including the number of images generated and server participation.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white mb-4">4. Data Sharing and Disclosure</h2>
              <p>We do not share your personal data with third parties except in the following circumstances:</p>
              <ul className="list-disc list-inside mt-2 space-y-2">
                <li>Legal Obligations: If required by law, regulation, or legal process, we may disclose your information to the relevant authorities.</li>
                <li>Service Providers: We may share data with third-party service providers that assist us in operating the bot, provided they adhere to strict confidentiality agreements.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white mb-4">5. Data Retention</h2>
              <ul className="list-disc list-inside space-y-2">
                <li>User Data: We retain user data only for as long as necessary to fulfill the purposes outlined in this policy.</li>
                <li>Generated Content: Generated images and prompts are only stored temporarily for processing and are deleted shortly after delivery.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white mb-4">6. Security</h2>
              <p>We take reasonable measures to protect your information from unauthorized access, use, or disclosure. However, please be aware that no security measures are perfect or impenetrable.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white mb-4">7. Your Rights</h2>
              <p>You have the following rights regarding your data:</p>
              <ul className="list-disc list-inside mt-2 space-y-2">
                <li>Access: You can request access to the data we hold about you.</li>
                <li>Correction: You can request correction of inaccurate data.</li>
                <li>Deletion: You can request deletion of your data, subject to our retention policies.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white mb-4">8. Changes to This Privacy Policy</h2>
              <p>We may update this Privacy Policy from time to time. Any changes will be posted with an updated "Last Updated" date. We encourage you to review this policy periodically to stay informed about how we are protecting your information.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white mb-4">9. Contact Us</h2>
              <p>If you have any questions or concerns about this Privacy Policy, please contact us at:</p>
              <div className="mt-2">
                <p>Email: contact@lykcloud.us.kg</p>
                <p>Website: lykcloud.me / lykcloud.us.kg</p>
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}

export default PrivacyPolicy;